import ICONS from './icons'
import IMAGES from './images'
import {
	DEFAULT_USER_SIGN_IN_FORM_VALUES,
	DEFAULT_USER_SIGN_UP_FORM_VALUES,
	CURRENCY_OPTIONS,
	FUEL_TYPE_OPTIONS,
	DEFAULT_FUEL_FORM_VALUES,
	DEFAULT_VEHICLE_FORM_VALUES
} from './formConstants'

export {
	ICONS,
	IMAGES,
	DEFAULT_USER_SIGN_IN_FORM_VALUES,
	DEFAULT_USER_SIGN_UP_FORM_VALUES,
	CURRENCY_OPTIONS,
	FUEL_TYPE_OPTIONS,
	DEFAULT_VEHICLE_FORM_VALUES,
	DEFAULT_FUEL_FORM_VALUES
}
